### ISSUE TITLE
Relighted image generation

### ISSUE THREAD

**Issue by HollyDQWang** [cgtuebingen/NeRD-Neural-Reflectance-Decomposition#10]
Congrats on such great work!

In Figure A6 as well as Figure 4 of the paper, a relighted scene under envmap and point light for specific object is captured. Would someone kindly explain to me how is the relighted image generated? Do we need to use a separate rendering for this step or can we get this result from the trained model?

**Comment by sunwenzhang1996** [comment]
hi i have the same problem. Did you solve it?
