### ISSUE TITLE
OpenEXR images are broken in released datasets

### ISSUE THREAD

**Issue by dkasuga** [cgtuebingen/NeRD-Neural-Reflectance-Decomposition#4]
Hello, thank you for your great work! 

I executed `download_datasets.py` and downloaded image datasets, but I found OpenEXR images in `synthetic` directory are broken. Does anybody have the same problem?

**Comment by vork** [comment]
It might be that the viewer is not capable of handling multi-channel EXR images. Try to use pyexr, which works for me.
