### ISSUE TITLE
Generating new SGs

### ISSUE THREAD

**Issue by CyxFTS** [cgtuebingen/NeRD-Neural-Reflectance-Decomposition#7]
Hey, thank you for the awesome work.

I want to test relighting with custom scenes, how can I convert an exr environment map into SGs?
I've tried the fitting script from [PhySG](https://github.com/Kai-46/PhySG/blob/master/code/envmaps/fit_envmap_with_sg.py). It looks like their SGs is not the same format as yours.

**Comment by wl0521** [comment]
same problem, how to convert exr enviroment map into SG?

**Comment by vork** [comment]
I've just added a new script to fit SGs. Run it with `python -m scripts.fit_sgs ENV_MAP_EXR_PATH --out_path SAVE_PATH --gpu 0`
